# train and val datasets (image directory or *.txt file with image paths)
train: ./datasets/traindata/images/train/
val: ./datasets/traindata/images/val/
# number of classes
nc: 2
# class names
names: ["equation","w"]